language: python
python:
  - "3.6"
# Command to install dependecies
install:
  - pip install git+https://github.com/UBC-MDS/BeautyPy
  - pip install -U pytest
  - pip install numpy
  - pip install scikit-image
  - pip install Pillow
  - pip install pandas

# Command to run tests
script: pytest
